# Generated by Django 3.1.7 on 2021-04-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0002_persons_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons_subjects',
            old_name='user_id',
            new_name='user',
        ),
    ]
