# Generated by Django 3.1.7 on 2021-04-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0004_auto_20210413_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons_subjects',
            old_name='user_id',
            new_name='user',
        ),
    ]
