# Generated by Django 3.1.7 on 2021-04-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0009_auto_20210414_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons_subjects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='persons_subjects',
            name='subject',
        ),
        migrations.AddField(
            model_name='persons_subjects',
            name='subject',
            field=models.ManyToManyField(to='directory_page.Subjects'),
        ),
        migrations.DeleteModel(
            name='Add_subjects',
        ),
    ]
