# Generated by Django 3.1.7 on 2021-04-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0011_auto_20210414_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons_subjects',
            options={'verbose_name': "Person's subject", 'verbose_name_plural': "Person's subjects"},
        ),
        migrations.RemoveField(
            model_name='persons_subjects',
            name='subject',
        ),
        migrations.AddField(
            model_name='persons_subjects',
            name='subject',
            field=models.ManyToManyField(to='directory_page.Subjects'),
        ),
    ]
