# Generated by Django 3.1.7 on 2021-04-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0014_auto_20210414_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons_subjects',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.subjects', unique=True),
        ),
    ]
