# Generated by Django 3.1.7 on 2021-04-14 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0015_auto_20210414_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons_subjects',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.subjects'),
        ),
        migrations.RemoveField(
            model_name='persons_subjects',
            name='user',
        ),
        migrations.AddField(
            model_name='persons_subjects',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
