# Generated by Django 3.1.7 on 2021-04-14 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0016_auto_20210414_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons_subjects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='persons_subjects',
            name='id',
        ),
        migrations.AddField(
            model_name='persons_subjects',
            name='id',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
