# Generated by Django 3.1.7 on 2021-04-14 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0016_auto_20210414_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persons_subjects',
            new_name='User_subjects',
        ),
    ]
