# Generated by Django 3.1.7 on 2021-04-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0017_auto_20210414_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_subjects',
            new_name='Persons_subjects',
        ),
    ]
