# Generated by Django 3.1.7 on 2021-04-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0022_auto_20210414_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person_subjects',
        ),
    ]
