# Generated by Django 3.1.7 on 2021-04-14 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0024_person_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_subjects',
            name='user',
        ),
        migrations.AddField(
            model_name='person_subjects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
