# Generated by Django 3.1.7 on 2021-04-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0025_auto_20210415_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person_subjects',
        ),
    ]
