# Generated by Django 3.1.7 on 2021-04-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0029_auto_20210415_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_subjects',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.subjects'),
        ),
    ]
