# Generated by Django 3.1.7 on 2021-04-23 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_semester_start', models.DateField(verbose_name='First semester start date')),
                ('first_semester_end', models.DateField(verbose_name='First semester end date')),
                ('second_semester_start', models.DateField(verbose_name='Second semester start date')),
                ('second_semester_end', models.DateField(verbose_name='Second semester end date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
