# Generated by Django 3.1.7 on 2021-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester_dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': "Person's date", 'verbose_name_plural': "Person's dates"},
        ),
        migrations.AlterField(
            model_name='dates',
            name='first_semester_end',
            field=models.DateTimeField(verbose_name='First semester end date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='first_semester_start',
            field=models.DateTimeField(verbose_name='First semester start date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='second_semester_end',
            field=models.DateTimeField(verbose_name='Second semester end date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='second_semester_start',
            field=models.DateTimeField(verbose_name='Second semester start date'),
        ),
    ]
