# Generated by Django 3.1.7 on 2021-04-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester_dates', '0002_auto_20210423_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='first_semester_end',
            field=models.DateField(verbose_name='First semester end date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='first_semester_start',
            field=models.DateField(verbose_name='First semester start date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='second_semester_end',
            field=models.DateField(verbose_name='Second semester end date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='second_semester_start',
            field=models.DateField(verbose_name='Second semester start date'),
        ),
    ]
