# Generated by Django 3.1.7 on 2021-04-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0030_auto_20210415_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='enter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField(null=True)),
                ('enter_date', models.DateField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.person_subjects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users mark',
                'verbose_name_plural': 'Users marks',
            },
        ),
    ]
