# Generated by Django 3.1.7 on 2021-04-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20210424_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter_marks',
            name='mark2',
        ),
    ]
