# Generated by Django 3.1.7 on 2021-04-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_remove_enter_marks_mark2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enter_marks',
            old_name='mark1',
            new_name='mark',
        ),
    ]
