# Generated by Django 3.1.7 on 2021-04-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_page', '0030_auto_20210415_2311'),
        ('enter', '0004_auto_20210426_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_marks',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.person_subjects'),
        ),
    ]
