# Generated by Django 3.1.7 on 2021-04-29 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory_page', '0030_auto_20210415_2311'),
        ('enter', '0006_auto_20210429_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_marks',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_page.person_subjects'),
        ),
        migrations.AlterField(
            model_name='enter_marks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
